# 配置数据源
spring:
  datasource:
    name: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
# 配置日志
logging:
  level:
    root: warn
    com.dyz.mybatisplus.dao: trace
  pattern:
    console: '%p%m%n'
# Mybatis-plus配置内容
mybatis-plus:
  #扫描resource目录下的mapper文件夹中的xml文件(多模块项目用classpath*)
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    use-column-label: true
  #全局类名
  type-aliases-package: com.dyz.mybatisplus.entity
  global-config:
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: uuid
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: not_null
      #驼峰下划线转换
      table-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1